Augmentation pipeline
ai-forever/sage pull request #14
Opened 2024-05-31 11:29 UTC by dodecaphony

2024-06-17 07:46 UTC, meduzick requested changes
Just a few more details, everything else is ok

2024-06-17 07:46 UTC, meduzick commented on pipeline_demo.py
Pls, make a similar notebook and put into sage/notebooks

2024-06-17 07:46 UTC, meduzick commented on sage/pipeline/augmentors.py
> +from typing import Optional
Not sure, but import from conventional typing may be better placed before import from sage package

2024-06-17 07:46 UTC, meduzick commented on sage/pipeline/pipeline.py
> +import random
import random has to be before import from typing I guess

2024-06-25 13:40 UTC, danil31219as requested changes

2024-06-25 13:40 UTC, danil31219as commented on sage/pipeline/pipeline.py
> +        self._add_all_augmentors()
You always add all the augmentors

2024-06-25 13:40 UTC, danil31219as commented on tests/test_pipeline.py
> +        pipeline.add_char_augmentor()
You've already added all kinds of augmentors

2024-06-25 13:40 UTC, danil31219as commented on tests/test_pipeline.py
> +        unittest.main()
Extra indentation, tests don't run, how did you test this code?

2024-06-25 13:40 UTC, danil31219as commented on sage/pipeline/config.py
> +        self.sbsc_lang = lang
duplicates __init__ method

2024-06-25 13:40 UTC, danil31219as commented on sage/pipeline/config.py
> +        self.sbsc_reference_dataset_split: str = "test"
Why is lang an argument, but everything else is fixed?

2024-06-25 13:40 UTC, danil31219as commented on sage/pipeline/config.py
> +            raise ValueError("Unsupported language. Supported languages are 'ru' and 'en'.")
not scalable, but not critical

2024-06-25 13:40 UTC, danil31219as commented on sage/pipeline/pipeline.py
> +        self.augmenters = [augmenter for augmenter in self.augmenters if not isinstance(augmenter, augmenter_type)]
When I work with the AugmentationPipeline class and its methods like add_char_augmenter, I don't know about the existence of augmenter types, but I have to get them somewhere

2024-06-25 13:40 UTC, danil31219as commented on sage/pipeline/pipeline.py
> +        self._add_all_augmenters()
why?

2024-06-25 13:40 UTC, danil31219as commented on sage/pipeline/pipeline.py
> +        random.shuffle(self.augmenters)
seed?

2024-06-25 13:40 UTC, danil31219as commented on sage/pipeline/pipeline.py
> +    def remove_augmenter(self, augmenter_type):
type of augmenter_type?

2024-06-25 13:40 UTC, danil31219as commented on tests/test_pipeline.py
> +        pipeline.set_order([0, 1, 2])  # All augmenters
maybe shuffled order?

2024-09-20 14:04 UTC, merged